<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'admin',
                'email' => 'lpc@admin.com',
                'email_verified_at' => NULL,
                'password' => bcrypt('password@lpc'),
                'phone' => NULL,
                'image' => NULL,
                'middel_name' => NULL,
                'last_name' => NULL,
                'current_role_id' => 1,
                'role' => 1,
                'company_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-09-09 06:40:42',
                'updated_at' => '2024-09-09 06:40:42',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            1 => 
            array (
                'id' => 43,
                'name' => 'test-company',
                'email' => 'test-company@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$o0qiefc0sLqvdwRMJxhEVunPBQk2N67xlOHaUPbUUss40d8whRbo6',
                'phone' => '123',
                'image' => '',
                'middel_name' => 'test',
                'last_name' => 'test',
                'current_role_id' => 5,
                'role' => 5,
                'company_id' => 3,
                'remember_token' => NULL,
                'created_at' => '2025-01-10 00:04:45',
                'updated_at' => '2025-01-10 00:04:45',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            2 => 
            array (
                'id' => 44,
                'name' => 'test-company-trainee',
                'email' => 'trainee@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$KfcI/DqbwNyM7vLzh9UzbujqAfJLqgUZ18QZNjgvjP0iBsLvUCxt.',
                'phone' => '123',
                'image' => '',
                'middel_name' => 'test',
                'last_name' => 'test',
                'current_role_id' => 3,
                'role' => 3,
                'company_id' => 3,
                'remember_token' => NULL,
                'created_at' => '2025-01-10 00:05:36',
                'updated_at' => '2025-01-10 00:05:36',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            3 => 
            array (
                'id' => 47,
                'name' => 'tt',
                'email' => 'ltc@admin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$eGhefzqUq666HqVB/kpbLuDi2sfQJVeUUKBh26ju8fmsGoIIZF0qq',
                'phone' => '00',
                'image' => NULL,
                'middel_name' => 't',
                'last_name' => 't',
                'current_role_id' => 4,
                'role' => 4,
                'company_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-01-10 11:52:09',
                'updated_at' => '2025-01-10 11:52:09',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            4 => 
            array (
                'id' => 54,
                'name' => 'Company',
                'email' => 'test@prokoders.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$D6RQwB7DKyz6k6M/JbFX2esKl7p1W1i1sTqGos7r//sacUc7ZgNgK',
                'phone' => '77777',
                'image' => '',
                'middel_name' => 'Test',
                'last_name' => 'Test',
                'current_role_id' => 5,
                'role' => 5,
                'company_id' => 4,
                'remember_token' => NULL,
                'created_at' => '2025-01-11 17:11:10',
                'updated_at' => '2025-01-11 17:11:10',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            5 => 
            array (
                'id' => 59,
                'name' => 'test-h',
                'email' => 'h_ezzo@prokoders.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$jtjn0zRxQJcGjrV.pyW6Pe6lnFLFgect3I52FQSZmBuvUr/PdkcNO',
                'phone' => '123',
                'image' => NULL,
                'middel_name' => 'hh',
                'last_name' => 'test',
                'current_role_id' => 4,
                'role' => 4,
                'company_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-01-12 19:32:40',
                'updated_at' => '2025-01-12 19:36:48',
                'telegram_chat_id' => NULL,
                'first_login' => 0,
            ),
            6 => 
            array (
                'id' => 60,
                'name' => 'Prokoders',
                'email' => 'm_hamdan@prokoders.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$kLK1JjrmAtjHNDT2sRNOMuMRy5Y.K2xeU/ZPtQBtmzwPWyDmGrbO2',
                'phone' => '123',
                'image' => NULL,
                'middel_name' => 'test',
                'last_name' => 'Test',
                'current_role_id' => 3,
                'role' => 3,
                'company_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-01-16 11:03:36',
                'updated_at' => '2025-02-12 14:30:01',
                'telegram_chat_id' => NULL,
                'first_login' => 0,
            ),
            7 => 
            array (
                'id' => 61,
                'name' => 'Mohammad',
                'email' => 'osama.addas1995@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$A9jKHCxHpON9jQNnDUH0yeA63jVFGXRHYdnoTULX5tGYnLf9VLwXG',
                'phone' => '946465046',
                'image' => 'media/1737301953.jpg',
                'middel_name' => 'Osama',
                'last_name' => 'Addas',
                'current_role_id' => 6,
                'role' => 6,
                'company_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-01-19 18:05:11',
                'updated_at' => '2025-01-19 18:05:11',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            8 => 
            array (
                'id' => 62,
                'name' => 'Addas',
                'email' => 'osama@lpcentre.work',
                'email_verified_at' => NULL,
                'password' => '$2y$12$WQibjK9hFZr.EOKMWx92Zutikhh5Y/EtnfP37rKTxBInB/dTNNcwC',
                'phone' => '946465046',
                'image' => '',
                'middel_name' => 'Osama',
                'last_name' => 'Addas',
                'current_role_id' => 3,
                'role' => 3,
                'company_id' => 4,
                'remember_token' => NULL,
                'created_at' => '2025-01-19 18:09:05',
                'updated_at' => '2025-01-19 18:09:05',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            9 => 
            array (
                'id' => 63,
                'name' => 'Mike',
                'email' => 'lpc-crm@prokoders.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$o6u5f2f6cLo3m5uvrjW/huTelX0osd0GLGgUO889EdGs04QrK2e9a',
                'phone' => '946465046',
                'image' => NULL,
                'middel_name' => 'S',
                'last_name' => 'LPC',
                'current_role_id' => 4,
                'role' => 4,
                'company_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-01-19 18:51:48',
                'updated_at' => '2025-01-19 18:59:42',
                'telegram_chat_id' => NULL,
                'first_login' => 0,
            ),
            10 => 
            array (
                'id' => 65,
                'name' => 'LMA',
                'email' => 'aa@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$7cvswXIZdVBF8vWNg4XPK.LNXrbjims6RDdfgtKovtJ3Ya/1XyxHS',
                'phone' => '946465046',
                'image' => '',
                'middel_name' => 'Company',
                'last_name' => 'Company',
                'current_role_id' => 5,
                'role' => 5,
                'company_id' => 4,
                'remember_token' => NULL,
                'created_at' => '2025-01-20 15:04:56',
                'updated_at' => '2025-01-20 15:04:56',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            11 => 
            array (
                'id' => 66,
                'name' => 'Mike',
                'email' => 'mike@lpcentre.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$I5.qp7PAcK2JF/8miMrIUOev8TNs8oImr.PdKsGCabPEFpabEzqRu',
                'phone' => '0554432901',
                'image' => '',
                'middel_name' => 'A',
                'last_name' => 'S',
                'current_role_id' => 3,
                'role' => 3,
                'company_id' => 3,
                'remember_token' => NULL,
                'created_at' => '2025-02-15 19:07:51',
                'updated_at' => '2025-02-15 19:07:51',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            12 => 
            array (
                'id' => 67,
                'name' => 'Mahmoud',
                'email' => 'm_hosain@prokoders.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$wgERk0azIfKpA4zIWif1i.//CJZJe5.FcamvVE8H1LpXkn0N2toV2',
                'phone' => '0988890576',
                'image' => '',
                'middel_name' => NULL,
                'last_name' => 'Hosain',
                'current_role_id' => 3,
                'role' => 3,
                'company_id' => 3,
                'remember_token' => NULL,
                'created_at' => '2025-02-16 12:56:17',
                'updated_at' => '2025-02-16 12:56:17',
                'telegram_chat_id' => NULL,
                'first_login' => 1,
            ),
            13 => 
            array (
                'id' => 68,
                'name' => 'Mahmoud',
                'email' => 'm_hosain1@prokoders.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zRmFXYnRrFVJ7r1FVXIJOuW657Nq09b0qIuW2Z7LO2qOJEphn4CuC',
                'phone' => '0988890577',
                'image' => NULL,
                'middel_name' => NULL,
                'last_name' => 'Hosain',
                'current_role_id' => 4,
                'role' => 4,
                'company_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-02-16 14:22:11',
                'updated_at' => '2025-02-16 14:31:55',
                'telegram_chat_id' => NULL,
                'first_login' => 0,
            ),
        ));
        
        
    }
}